/* ============ Fondré Studio — i18n (SK base → EN / DE / NL) ============ */
(function () {
  // key = exact Slovak source (trimmed). Names, brands, tools, emails, numbers are left untranslated.
  var T = {
    // ---- navbar / footer / shared ----
    "Digital products designers": { EN: "Digital products designers", DE: "Designer digitaler Produkte", NL: "Ontwerpers van digitale producten" },
    "Projekty": { EN: "Projects", DE: "Projekte", NL: "Projecten" },
    "O nás": { EN: "About", DE: "Über uns", NL: "Over ons" },
    "Kontaktujte nás": { EN: "Contact us", DE: "Kontakt", NL: "Contact" },
    "Domov": { EN: "Home", DE: "Startseite", NL: "Home" },
    "Ochrana súkromia": { EN: "Privacy policy", DE: "Datenschutz", NL: "Privacybeleid" },
    "Pravidlá používania": { EN: "Terms of use", DE: "Nutzungsbedingungen", NL: "Gebruiksvoorwaarden" },
    "2026 Created by Fondré Studio, All rights reserved.": { EN: "2026 Created by Fondré Studio, All rights reserved.", DE: "2026 Erstellt von Fondré Studio, alle Rechte vorbehalten.", NL: "2026 Gemaakt door Fondré Studio, alle rechten voorbehouden." },
    "© 2026 Created by Fondré Studio, All rights reserved.": { EN: "© 2026 Created by Fondré Studio, All rights reserved.", DE: "© 2026 Erstellt von Fondré Studio, alle Rechte vorbehalten.", NL: "© 2026 Gemaakt door Fondré Studio, alle rechten voorbehouden." },

    // ---- contact block ----
    "Máte projekt na mysli?": { EN: "Have a project in mind?", DE: "Haben Sie ein Projekt im Kopf?", NL: "Heb je een project in gedachten?" },
    "Celé meno/spoločnosť": { EN: "Full name/company", DE: "Vollständiger Name/Firma", NL: "Volledige naam/bedrijf" },
    "Vaše meno/spoločnosť": { EN: "Your name/company", DE: "Ihr Name/Firma", NL: "Jouw naam/bedrijf" },
    "Emailová adresa": { EN: "Email address", DE: "E-Mail-Adresse", NL: "E-mailadres" },
    "Popis projektu/správa": { EN: "Project description/message", DE: "Projektbeschreibung/Nachricht", NL: "Projectbeschrijving/bericht" },
    "Napíšte krátky popis projektu.": { EN: "Write a short project description.", DE: "Schreiben Sie eine kurze Projektbeschreibung.", NL: "Schrijf een korte projectbeschrijving." },
    "Odoslať": { EN: "Send", DE: "Senden", NL: "Verstuur" },
    "Spojme sa": { EN: "Let's talk", DE: "Sprechen wir", NL: "Laten we praten" },
    "k vášmu": { EN: "about your", DE: "über Ihr", NL: "over jouw" },
    "projektu": { EN: "project", DE: "Projekt", NL: "project" },

    // ---- home hero ----
    "Dizajn, ktorý prináša": { EN: "Design that brings", DE: "Design mit", NL: "Design met" },
    "rast": { EN: "growth", DE: "Wachstum", NL: "groei" },
    "Tvoríme digitálne produkty,": { EN: "We build digital products,", DE: "Wir schaffen digitale Produkte,", NL: "We bouwen digitale producten," },
    "weby s dôrazom na performance, jasnosť": { EN: "websites focused on performance, clarity", DE: "Websites mit Fokus auf Performance, Klarheit", NL: "websites gericht op prestaties, helderheid" },
    "a charakter.": { EN: "and character.", DE: "und Charakter.", NL: "en karakter." },
    "Tvoríme digitálne produkty, weby s dôrazom na performance, jasnosť a charakter.": { EN: "We build digital products, websites focused on performance, clarity and character.", DE: "Wir schaffen digitale Produkte, Websites mit Fokus auf Performance, Klarheit und Charakter.", NL: "We bouwen digitale producten, websites gericht op prestaties, helderheid en karakter." },

    // ---- home stats + facts ----
    "8 years": { EN: "8 years", DE: "8 Jahre", NL: "8 jaar" },
    "Digitálne projekty posilnené strategickým dizajnom": { EN: "Digital projects powered by strategic design", DE: "Digitale Projekte, gestärkt durch strategisches Design", NL: "Digitale projecten versterkt door strategisch design" },
    "Priemerný nárast zapojenia používateľov": { EN: "Average increase in user engagement", DE: "Durchschnittliche Steigerung des Nutzer-Engagements", NL: "Gemiddelde toename in gebruikersbetrokkenheid" },
    "Roky skúseností v odvetví": { EN: "Years of industry experience", DE: "Jahre Branchenerfahrung", NL: "Jaren branche-ervaring" },
    "Spokojnosť s realizáciou projektu": { EN: "Satisfaction with project delivery", DE: "Zufriedenheit mit der Projektumsetzung", NL: "Tevredenheid met projectoplevering" },
    "SÍDLO": { EN: "LOCATION", DE: "STANDORT", NL: "LOCATIE" },
    "Bratislava a Viedeň": { EN: "Bratislava and Vienna", DE: "Bratislava und Wien", NL: "Bratislava en Wenen" },
    "JAZYKY": { EN: "LANGUAGES", DE: "SPRACHEN", NL: "TALEN" },
    "Slovak, English, Dutch, German": { EN: "Slovak, English, Dutch, German", DE: "Slowakisch, Englisch, Niederländisch, Deutsch", NL: "Slowaaks, Engels, Nederlands, Duits" },
    "ŠPECIALIZÁCIA": { EN: "SPECIALIZATION", DE: "SPEZIALISIERUNG", NL: "SPECIALISATIE" },
    "Produktové UI/UX, designové systémy": { EN: "Product UI/UX, design systems", DE: "Produkt-UI/UX, Designsysteme", NL: "Product-UI/UX, designsystemen" },
    "OTVORENÍ SPOLUPRÁCI": { EN: "OPEN TO COLLABORATION", DE: "OFFEN FÜR ZUSAMMENARBEIT", NL: "OPEN VOOR SAMENWERKING" },
    "Medium size freelance projects": { EN: "Medium size freelance projects", DE: "Freelance-Projekte mittlerer Größe", NL: "Freelanceprojecten van gemiddelde omvang" },

    // ---- home projects ----
    "Projekty na,": { EN: "Projects", DE: "Projekte,", NL: "Projecten" },
    "ktoré sme": { EN: "we are", DE: "auf die wir", NL: "waar we" },
    "hrdí": { EN: "proud of", DE: "stolz sind", NL: "trots op zijn" },
    "Produktový dizajn · UX/UI · Dizajnový systém": { EN: "Product design · UX/UI · Design system", DE: "Produktdesign · UX/UI · Designsystem", NL: "Productdesign · UX/UI · Designsysteem" },
    "Webový dizajn · Branding · Audio platforma": { EN: "Web design · Branding · Audio platform", DE: "Webdesign · Branding · Audioplattform", NL: "Webdesign · Branding · Audioplatform" },
    "Gamifikačný panel · Dizajnový systém · UX": { EN: "Gamification panel · Design system · UX", DE: "Gamification-Panel · Designsystem · UX", NL: "Gamification-paneel · Designsysteem · UX" },
    "Produktový dizajn · Vizuálna identita · Web": { EN: "Product design · Visual identity · Web", DE: "Produktdesign · Visuelle Identität · Web", NL: "Productdesign · Visuele identiteit · Web" },
    "Otters tech conference ‘25": { EN: "Otters tech conference ‘25", DE: "Otters Tech-Konferenz ‘25", NL: "Otters tech-conferentie ‘25" },

    // ---- home services ----
    "Čo robíme": { EN: "What we do", DE: "Was wir tun", NL: "Wat we doen" },
    "Produktový design": { EN: "Product design", DE: "Produktdesign", NL: "Productdesign" },
    "Designové systémy": { EN: "Design systems", DE: "Designsysteme", NL: "Designsystemen" },
    "Vizuálny smer rozhraní": { EN: "Visual direction of interfaces", DE: "Visuelle Ausrichtung von Interfaces", NL: "Visuele richting van interfaces" },
    "Webový design": { EN: "Web design", DE: "Webdesign", NL: "Webdesign" },
    "Vizuálna identita pre digitálne produkty": { EN: "Visual identity for digital products", DE: "Visuelle Identität für digitale Produkte", NL: "Visuele identiteit voor digitale producten" },
    "Konzultácie a audity": { EN: "Consulting and audits", DE: "Beratung und Audits", NL: "Advies en audits" },
    "Kompletný UI/UX dizajn produktov — od wireframov po pixel-perfect rozhrania pripravené na vývoj. Prehľadnosť, efektívnosť a vizuálna kvalita.": { EN: "Complete UI/UX product design — from wireframes to pixel-perfect interfaces ready for development. Clarity, efficiency and visual quality.", DE: "Komplettes UI/UX-Produktdesign — von Wireframes bis zu pixelgenauen, entwicklungsbereiten Interfaces. Klarheit, Effizienz und visuelle Qualität.", NL: "Compleet UI/UX-productdesign — van wireframes tot pixelperfecte interfaces klaar voor ontwikkeling. Helderheid, efficiëntie en visuele kwaliteit." },
    "Zdieľané knižnice, komponenty a tokeny vo Figme. Staviame systémy, ktoré urýchlia dodávanie a udržia konzistentnosť naprieč produktom.": { EN: "Shared libraries, components and tokens in Figma. We build systems that speed up delivery and keep consistency across the product.", DE: "Gemeinsame Bibliotheken, Komponenten und Tokens in Figma. Wir bauen Systeme, die die Auslieferung beschleunigen und Konsistenz im Produkt wahren.", NL: "Gedeelde bibliotheken, componenten en tokens in Figma. We bouwen systemen die de oplevering versnellen en consistentie in het product bewaken." },
    "Vizuálny štýl pre digitálne rozhrania — od typografie cez paletu až po ikonografiu. Koherentný jazyk, ktorý posilní rozpoznateľnosť.": { EN: "Visual style for digital interfaces — from typography through palette to iconography. A coherent language that strengthens recognizability.", DE: "Visueller Stil für digitale Interfaces — von Typografie über Palette bis zur Ikonografie. Eine kohärente Sprache, die die Wiedererkennbarkeit stärkt.", NL: "Visuele stijl voor digitale interfaces — van typografie via palet tot iconografie. Een coherente taal die de herkenbaarheid versterkt." },
    "Prezentačné weby pre značky a startupy s dôrazom na typografiu, rýchlosť a responzívnosť. Príbeh značky na obrazovke.": { EN: "Presentation websites for brands and startups focused on typography, speed and responsiveness. The brand story on screen.", DE: "Präsentationswebsites für Marken und Startups mit Fokus auf Typografie, Geschwindigkeit und Responsivität. Die Markengeschichte auf dem Bildschirm.", NL: "Presentatiewebsites voor merken en startups gericht op typografie, snelheid en responsiviteit. Het merkverhaal op het scherm." },
    "Vizuálna identita pre digitálne produkty a rastúce firmy. Audit existujúceho brandu a návrh nových elementov, ktoré spolu fungujú.": { EN: "Visual identity for digital products and growing companies. An audit of the existing brand and the design of new elements that work together.", DE: "Visuelle Identität für digitale Produkte und wachsende Unternehmen. Ein Audit der bestehenden Marke und die Gestaltung neuer, zusammenwirkender Elemente.", NL: "Visuele identiteit voor digitale producten en groeiende bedrijven. Een audit van het bestaande merk en het ontwerp van nieuwe elementen die samenwerken." },
    "UX/UI review, audit rozhraní a produktová stratégia. Skúsený pohľad zvonka, keď potrebujete praktickú radu.": { EN: "UX/UI review, interface audit and product strategy. An experienced outside view when you need practical advice.", DE: "UX/UI-Review, Interface-Audit und Produktstrategie. Ein erfahrener Blick von außen, wenn Sie praktischen Rat brauchen.", NL: "UX/UI-review, interface-audit en productstrategie. Een ervaren blik van buitenaf wanneer je praktisch advies nodig hebt." },

    // ---- home cta / testimonials / partners ----
    "Máte nápad?": { EN: "Got an idea?", DE: "Haben Sie eine Idee?", NL: "Heb je een idee?" },
    "Dohodnime si stretnutie": { EN: "Let's set up a meeting", DE: "Vereinbaren wir ein Treffen", NL: "Laten we een afspraak maken" },
    "Máte nápad? Dohodnime si stretnutie": { EN: "Got an idea? Let's set up a meeting", DE: "Haben Sie eine Idee? Vereinbaren wir ein Treffen", NL: "Heb je een idee? Laten we een afspraak maken" },
    "Čo sa o nás": { EN: "What they say about", DE: "Was man über uns", NL: "Wat men over ons" },
    "hovorí": { EN: "us", DE: "sagt", NL: "zegt" },
    "“ Spolupracujeme na viacerých projektoch. Najviac oceňujeme schopnosť vidieť celý produkt ako celistvý systém. Dizajn nikdy nie je len vizuálny, ale pomáha nám zjednotiť celé používateľské prostredie popri samotnom developmente.“": { EN: "“ We collaborate on several projects. What we value most is the ability to see the whole product as a coherent system. The design is never just visual — it helps us unify the entire user experience alongside the development itself.“", DE: "„ Wir arbeiten an mehreren Projekten zusammen. Am meisten schätzen wir die Fähigkeit, das gesamte Produkt als kohärentes System zu sehen. Das Design ist nie nur visuell — es hilft uns, die gesamte Nutzererfahrung neben der Entwicklung selbst zu vereinheitlichen.“", NL: "“ We werken samen aan meerdere projecten. Wat we het meest waarderen, is het vermogen om het hele product als een samenhangend systeem te zien. Het ontwerp is nooit alleen visueel — het helpt ons de hele gebruikerservaring te verenigen naast de ontwikkeling zelf.“" },
    "SOFTWARE DEVELOPER": { EN: "SOFTWARE DEVELOPER", DE: "SOFTWAREENTWICKLERIN", NL: "SOFTWAREONTWIKKELAAR" },
    "Spolupráce, o ktorých by ste mali vedieť": { EN: "Collaborations you should know about", DE: "Kooperationen, die Sie kennen sollten", NL: "Samenwerkingen die je moet kennen" },

    // ---- projekty page ----
    "Bližší pohľad na projekty,": { EN: "A closer look at the projects", DE: "Ein näherer Blick auf die Projekte,", NL: "Een nadere blik op de projecten," },
    "ktoré sme realizovali": { EN: "we have delivered", DE: "die wir umgesetzt haben", NL: "die we hebben gerealiseerd" },
    "Bližší pohľad na projekty, ktoré sme realizovali": { EN: "A closer look at the projects we have delivered", DE: "Ein näherer Blick auf die Projekte, die wir umgesetzt haben", NL: "Een nadere blik op de projecten die we hebben gerealiseerd" },
    "Vybrané projekty z produktového dizajnu, webov a širších systémov — realizované samostatne aj v rámci spolupráce s Drixton a agentúrnymi partnermi.": { EN: "Selected projects across product design, websites and broader systems — delivered independently and in collaboration with Drixton and agency partners.", DE: "Ausgewählte Projekte aus Produktdesign, Websites und umfassenderen Systemen — eigenständig sowie in Zusammenarbeit mit Drixton und Agenturpartnern umgesetzt.", NL: "Geselecteerde projecten uit productdesign, websites en bredere systemen — zelfstandig en in samenwerking met Drixton en bureaupartners gerealiseerd." },
    "Všetko": { EN: "All", DE: "Alle", NL: "Alle" },
    "Produktový dizajn · UX/UI": { EN: "Product design · UX/UI", DE: "Produktdesign · UX/UI", NL: "Productdesign · UX/UI" },
    "Webový dizajn · Branding": { EN: "Web design · Branding", DE: "Webdesign · Branding", NL: "Webdesign · Branding" },
    "Gamifikácia · Dizajnový systém": { EN: "Gamification · Design system", DE: "Gamification · Designsystem", NL: "Gamification · Designsysteem" },
    "Produktový dizajn · Vizuálna identita": { EN: "Product design · Visual identity", DE: "Produktdesign · Visuelle Identität", NL: "Productdesign · Visuele identiteit" },

    // ---- o nas page ----
    "Dizajnujeme digitálne produkty,": { EN: "We design digital products,", DE: "Wir gestalten digitale Produkte,", NL: "We ontwerpen digitale producten," },
    "s dôrazom na výkon,": { EN: "focused on performance,", DE: "mit Fokus auf Leistung,", NL: "gericht op prestaties," },
    "rozpoznateľnosť a jasnosť": { EN: "recognizability and clarity", DE: "Wiedererkennbarkeit und Klarheit", NL: "herkenbaarheid en helderheid" },
    "Dizajnujeme digitálne produkty, s dôrazom na výkon, rozpoznateľnosť a jasnosť": { EN: "We design digital products, focused on performance, recognizability and clarity", DE: "Wir gestalten digitale Produkte, mit Fokus auf Leistung, Wiedererkennbarkeit und Klarheit", NL: "We ontwerpen digitale producten, gericht op prestaties, herkenbaarheid en helderheid" },
    "Sme dizajnové štúdio, ktoré stojí za digitálnymi produktmi s dôrazom na detail, presnosť a reálnu použiteľnosť. Spolupracujeme s viacerými technologickými spoločnosťami a spoločne prepájame dizajn a technológie tak, aby výsledok fungoval rovnako dobre pre používateľov aj pre vývojárske tímy.": { EN: "We are a design studio behind digital products with an emphasis on detail, precision and real usability. We work with several technology companies and together we connect design and technology so the result works equally well for users and for development teams.", DE: "Wir sind ein Designstudio hinter digitalen Produkten mit Fokus auf Detail, Präzision und echte Benutzbarkeit. Wir arbeiten mit mehreren Technologieunternehmen zusammen und verbinden Design und Technologie so, dass das Ergebnis für Nutzer wie für Entwicklungsteams gleichermaßen gut funktioniert.", NL: "Wij zijn een designstudio achter digitale producten met nadruk op detail, precisie en echte bruikbaarheid. We werken samen met meerdere technologiebedrijven en verbinden design en technologie zó dat het resultaat even goed werkt voor gebruikers als voor ontwikkelteams." },
    "Ako rozmýšľame o dizajne": { EN: "How we think about design", DE: "Wie wir über Design denken", NL: "Hoe wij over design denken" },
    "Dizajn pre nás nie je len o vizuáli. Je to spôsob myslenia - ako zjednodušiť zložité, usporiadať chaos a vytvoriť prostredie, v ktorom sa ľudia okamžite zorientujú.": { EN: "For us, design is not only about visuals. It is a way of thinking — how to simplify the complex, organize chaos and create an environment where people instantly find their way.", DE: "Design ist für uns nicht nur Optik. Es ist eine Denkweise — wie man Komplexes vereinfacht, Chaos ordnet und eine Umgebung schafft, in der sich Menschen sofort zurechtfinden.", NL: "Voor ons gaat design niet alleen over het visuele. Het is een manier van denken — hoe je het complexe vereenvoudigt, chaos ordent en een omgeving creëert waarin mensen meteen hun weg vinden." },
    "Pracujeme na produktových rozhraniach, webových platformách a dizajnových systémoch, kde je kľúčová prehľadnosť a konzistentnosť.": { EN: "We work on product interfaces, web platforms and design systems where clarity and consistency are key.", DE: "Wir arbeiten an Produkt-Interfaces, Webplattformen und Designsystemen, bei denen Übersichtlichkeit und Konsistenz entscheidend sind.", NL: "We werken aan productinterfaces, webplatforms en designsystemen waar overzichtelijkheid en consistentie cruciaal zijn." },
    "Nečakáme na dokonalé podmienky. Často začíname s existujúcim backendom, obmedzeným rozpočtom alebo smerom, ktorý sa ešte len formuje. Tieto výzvy berieme ako súčasť hry - rovnako ako v športe, kde presnosť a disciplína rozhodujú o výsledku.": { EN: "We don't wait for perfect conditions. We often start with an existing backend, a limited budget or a direction that is still taking shape. We take these challenges as part of the game — just like in sport, where precision and discipline decide the outcome.", DE: "Wir warten nicht auf perfekte Bedingungen. Oft beginnen wir mit einem bestehenden Backend, einem begrenzten Budget oder einer Richtung, die sich erst noch formt. Diese Herausforderungen nehmen wir als Teil des Spiels — wie im Sport, wo Präzision und Disziplin über das Ergebnis entscheiden.", NL: "We wachten niet op perfecte omstandigheden. Vaak beginnen we met een bestaande backend, een beperkt budget of een richting die nog vorm krijgt. Deze uitdagingen zien we als onderdeel van het spel — net als in de sport, waar precisie en discipline de uitkomst bepalen." },
    "Pracovné skúsenosti": { EN: "Work experience", DE: "Berufserfahrung", NL: "Werkervaring" },
    "Spolupráce a klienti": { EN: "Collaborations and clients", DE: "Kooperationen und Kunden", NL: "Samenwerkingen en klanten" },
    "UX/UI Dizajnér · Woeva": { EN: "UX/UI Designer · Woeva", DE: "UX/UI-Designerin · Woeva", NL: "UX/UI-ontwerper · Woeva" },
    "Produktový dizajnér · PulseSound": { EN: "Product Designer · PulseSound", DE: "Produktdesignerin · PulseSound", NL: "Productontwerper · PulseSound" },
    "Dizajnér · Spolupráca s Drixton": { EN: "Designer · Collaboration with Drixton", DE: "Designerin · Zusammenarbeit mit Drixton", NL: "Ontwerper · Samenwerking met Drixton" },
    "Grafický dizajn · Freelance": { EN: "Graphic design · Freelance", DE: "Grafikdesign · Freelance", NL: "Grafisch ontwerp · Freelance" },
    "2024 – Súčasnosť": { EN: "2024 – Present", DE: "2024 – Heute", NL: "2024 – Heden" },
    "2021 – Súčasnosť": { EN: "2021 – Present", DE: "2021 – Heute", NL: "2021 – Heden" },
    "Drixton · Technologický partner": { EN: "Drixton · Technology partner", DE: "Drixton · Technologiepartner", NL: "Drixton · Technologiepartner" },
    "PlayStation · Produktový dizajn": { EN: "PlayStation · Product design", DE: "PlayStation · Produktdesign", NL: "PlayStation · Productdesign" },
    "Woeva · UX/UI pre platformu": { EN: "Woeva · UX/UI for the platform", DE: "Woeva · UX/UI für die Plattform", NL: "Woeva · UX/UI voor het platform" },
    "Herbert · Vizuálna identita, Web": { EN: "Herbert · Visual identity, Web", DE: "Herbert · Visuelle Identität, Web", NL: "Herbert · Visuele identiteit, Web" },
    "V offline svete": { EN: "In the offline world", DE: "In der Offline-Welt", NL: "In de offline wereld" },
    "Veríme, že dobrý dizajn nevzniká náhodou. Je výsledkom premýšľania, disciplíny a pochopenia ľudí, ktorí ho budú používať. Inšpirujeme sa športom, technológiami aj hudbou - svetmi, kde rozhodujú detaily, konzistentnosť a neustále zlepšovanie. Ku každému projektu pristupujeme ako partneri, pretože naším cieľom nie je len vytvoriť pekný dizajn, ale produkt, ktorý bude fungovať.": { EN: "We believe good design doesn't happen by chance. It is the result of thinking, discipline and understanding the people who will use it. We draw inspiration from sport, technology and music — worlds where details, consistency and constant improvement matter. We approach every project as partners, because our goal is not just to create beautiful design, but a product that works.", DE: "Wir glauben, dass gutes Design nicht durch Zufall entsteht. Es ist das Ergebnis von Denken, Disziplin und dem Verständnis der Menschen, die es nutzen werden. Wir lassen uns von Sport, Technik und Musik inspirieren — Welten, in denen Details, Konsistenz und ständige Verbesserung zählen. Jedes Projekt gehen wir als Partner an, denn unser Ziel ist nicht nur schönes Design, sondern ein Produkt, das funktioniert.", NL: "We geloven dat goed design niet toevallig ontstaat. Het is het resultaat van denken, discipline en begrip van de mensen die het zullen gebruiken. We laten ons inspireren door sport, technologie en muziek — werelden waarin details, consistentie en voortdurende verbetering tellen. Elk project benaderen we als partners, want ons doel is niet alleen mooi design, maar een product dat werkt." },
    "Milujeme šport, dogs v office, sme nadšení motoršportom a hudbu máme pustenú all day all night.": { EN: "We love sport, dogs in the office, we're passionate about motorsport and the music is on all day all night.", DE: "Wir lieben Sport, Hunde im Büro, wir sind begeistert vom Motorsport und die Musik läuft all day all night.", NL: "We houden van sport, honden op kantoor, we zijn gek op motorsport en de muziek staat all day all night aan." },
    "Motorsports": { EN: "Motorsports", DE: "Motorsport", NL: "Motorsport" },
    "Pozemný hokej": { EN: "Field hockey", DE: "Feldhockey", NL: "Veldhockey" },
    "Psy a hory": { EN: "Dogs and mountains", DE: "Hunde und Berge", NL: "Honden en bergen" },
    "Beh a hudba všade": { EN: "Running and music everywhere", DE: "Laufen und Musik überall", NL: "Hardlopen en muziek overal" },

    // ---- legal: privacy ----
    "Vaše súkromie je pre nás dôležité. Posledná aktualizácia: 7. júl 2026.": { EN: "Your privacy matters to us. Last updated: 7 July 2026.", DE: "Ihre Privatsphäre ist uns wichtig. Zuletzt aktualisiert: 7. Juli 2026.", NL: "Jouw privacy is belangrijk voor ons. Laatst bijgewerkt: 7 juli 2026." },
    "1. Úvod": { EN: "1. Introduction", DE: "1. Einführung", NL: "1. Inleiding" },
    "Fondré Studio („my\", „nás\", „naše\") prevádzkuje túto webovú stránku. Tento dokument vysvetľuje, aké osobné údaje spracúvame, na aký účel, ako s nimi nakladáme a aké práva máte v súvislosti s ich spracovaním v súlade s Nariadením (EÚ) 2016/679 (GDPR) a zákonom č. 18/2018 Z. z. o ochrane osobných údajov.": { EN: "Fondré Studio (\"we\", \"us\", \"our\") operates this website. This document explains what personal data we process, for what purpose, how we handle it and what rights you have regarding its processing in accordance with Regulation (EU) 2016/679 (GDPR) and Act No. 18/2018 Coll. on the protection of personal data.", DE: "Fondré Studio („wir\", „uns\", „unser\") betreibt diese Website. Dieses Dokument erklärt, welche personenbezogenen Daten wir verarbeiten, zu welchem Zweck, wie wir damit umgehen und welche Rechte Sie hinsichtlich der Verarbeitung gemäß der Verordnung (EU) 2016/679 (DSGVO) und dem Gesetz Nr. 18/2018 GBl. über den Schutz personenbezogener Daten haben.", NL: "Fondré Studio (\"wij\", \"ons\", \"onze\") beheert deze website. Dit document legt uit welke persoonsgegevens we verwerken, voor welk doel, hoe we ermee omgaan en welke rechten je hebt met betrekking tot de verwerking, in overeenstemming met Verordening (EU) 2016/679 (AVG) en Wet nr. 18/2018 Coll. inzake de bescherming van persoonsgegevens." },
    "2. Aké údaje spracúvame": { EN: "2. What data we process", DE: "2. Welche Daten wir verarbeiten", NL: "2. Welke gegevens we verwerken" },
    "Spracúvame len údaje, ktoré nám dobrovoľne poskytnete prostredníctvom kontaktného formulára:": { EN: "We only process data you voluntarily provide through the contact form:", DE: "Wir verarbeiten nur Daten, die Sie uns freiwillig über das Kontaktformular übermitteln:", NL: "We verwerken alleen gegevens die je vrijwillig via het contactformulier verstrekt:" },
    "meno alebo názov spoločnosti,": { EN: "name or company name,", DE: "Name oder Firmenname,", NL: "naam of bedrijfsnaam," },
    "emailová adresa,": { EN: "email address,", DE: "E-Mail-Adresse,", NL: "e-mailadres," },
    "obsah správy a popis vášho projektu.": { EN: "the content of the message and a description of your project.", DE: "der Inhalt der Nachricht und eine Beschreibung Ihres Projekts.", NL: "de inhoud van het bericht en een beschrijving van je project." },
    "Automaticky môžeme spracúvať technické údaje ako IP adresu, typ prehliadača a základné štatistiky o návštevnosti.": { EN: "We may automatically process technical data such as IP address, browser type and basic traffic statistics.", DE: "Automatisch können wir technische Daten wie IP-Adresse, Browsertyp und grundlegende Zugriffsstatistiken verarbeiten.", NL: "We kunnen automatisch technische gegevens verwerken, zoals IP-adres, browsertype en basisstatistieken over bezoek." },
    "3. Účel a právny základ spracovania": { EN: "3. Purpose and legal basis of processing", DE: "3. Zweck und Rechtsgrundlage der Verarbeitung", NL: "3. Doel en rechtsgrondslag van de verwerking" },
    "Údaje z formulára používame výhradne na to, aby sme vás mohli kontaktovať a odpovedať na váš dopyt. Právnym základom je náš oprávnený záujem odpovedať na vašu žiadosť, prípadne kroky pred uzavretím zmluvy.": { EN: "We use the form data solely to contact you and respond to your enquiry. The legal basis is our legitimate interest in responding to your request, or steps prior to entering into a contract.", DE: "Wir verwenden die Formulardaten ausschließlich, um Sie zu kontaktieren und Ihre Anfrage zu beantworten. Rechtsgrundlage ist unser berechtigtes Interesse, auf Ihre Anfrage zu antworten, bzw. Schritte vor Vertragsabschluss.", NL: "We gebruiken de formuliergegevens uitsluitend om contact met je op te nemen en je vraag te beantwoorden. De rechtsgrondslag is ons gerechtvaardigd belang om op je verzoek te reageren, of stappen voorafgaand aan een overeenkomst." },
    "Údaje z formulára používame výhradne na to, aby sme vás mohli kontaktovať a odpovedať na váš dopyt. Právnym základom je náš oprávnený záujem odpovedať na vašu žiadosť, prípadne kroky pred uzavretím zmluvy. Údaje nepoužívame na automatizované rozhodovanie ani profilovanie.": { EN: "We use the form data solely to contact you and respond to your enquiry. The legal basis is our legitimate interest in responding to your request, or steps prior to entering into a contract. We do not use the data for automated decision-making or profiling.", DE: "Wir verwenden die Formulardaten ausschließlich, um Sie zu kontaktieren und Ihre Anfrage zu beantworten. Rechtsgrundlage ist unser berechtigtes Interesse, auf Ihre Anfrage zu antworten, bzw. Schritte vor Vertragsabschluss. Die Daten nutzen wir weder für automatisierte Entscheidungen noch für Profiling.", NL: "We gebruiken de formuliergegevens uitsluitend om contact met je op te nemen en je vraag te beantwoorden. De rechtsgrondslag is ons gerechtvaardigd belang om op je verzoek te reageren, of stappen voorafgaand aan een overeenkomst. We gebruiken de gegevens niet voor geautomatiseerde besluitvorming of profilering." },
    "4. Súbory cookies": { EN: "4. Cookies", DE: "4. Cookies", NL: "4. Cookies" },
    "Stránka používa iba nevyhnutné technické cookies potrebné pre jej správne fungovanie. Analytické alebo marketingové cookies nasadzujeme len s vaším súhlasom, ktorý môžete kedykoľvek odvolať v nastaveniach prehliadača.": { EN: "The site uses only essential technical cookies required for it to work properly. We deploy analytical or marketing cookies only with your consent, which you can withdraw at any time in your browser settings.", DE: "Die Seite verwendet nur notwendige technische Cookies, die für ihre ordnungsgemäße Funktion erforderlich sind. Analyse- oder Marketing-Cookies setzen wir nur mit Ihrer Einwilligung ein, die Sie jederzeit in den Browsereinstellungen widerrufen können.", NL: "De site gebruikt alleen essentiële technische cookies die nodig zijn om goed te functioneren. Analytische of marketingcookies plaatsen we alleen met jouw toestemming, die je op elk moment in je browserinstellingen kunt intrekken." },
    "Stránka používa iba nevyhnutné technické cookies potrebné pre jej správne fungovanie. Analytické alebo marketingové cookies nasadzujeme len s vaším súhlasom.": { EN: "The site uses only essential technical cookies required for it to work properly. We deploy analytical or marketing cookies only with your consent.", DE: "Die Seite verwendet nur notwendige technische Cookies, die für ihre ordnungsgemäße Funktion erforderlich sind. Analyse- oder Marketing-Cookies setzen wir nur mit Ihrer Einwilligung ein.", NL: "De site gebruikt alleen essentiële technische cookies die nodig zijn om goed te functioneren. Analytische of marketingcookies plaatsen we alleen met jouw toestemming." },
    "5. Zdieľanie a doba uchovávania": { EN: "5. Sharing and retention period", DE: "5. Weitergabe und Speicherdauer", NL: "5. Delen en bewaartermijn" },
    "Vaše údaje neposkytujeme tretím stranám na marketingové účely. Môžu byť sprístupnené len dôveryhodným spracovateľom (napr. poskytovateľ hostingu alebo emailovej služby) v nevyhnutnom rozsahu. Údaje uchovávame len po dobu nevyhnutnú na vybavenie vášho dopytu, najviac 24 mesiacov, ak zákon nevyžaduje inak.": { EN: "We do not share your data with third parties for marketing purposes. It may be made available only to trusted processors (e.g. a hosting or email service provider) to the necessary extent. We retain the data only for as long as needed to handle your enquiry, at most 24 months, unless the law requires otherwise.", DE: "Wir geben Ihre Daten nicht zu Marketingzwecken an Dritte weiter. Sie können nur vertrauenswürdigen Auftragsverarbeitern (z. B. Hosting- oder E-Mail-Dienstleistern) im erforderlichen Umfang zugänglich gemacht werden. Wir speichern die Daten nur so lange, wie es zur Bearbeitung Ihrer Anfrage nötig ist, höchstens 24 Monate, sofern das Gesetz nichts anderes verlangt.", NL: "We delen je gegevens niet met derden voor marketingdoeleinden. Ze kunnen alleen in de noodzakelijke mate beschikbaar worden gesteld aan vertrouwde verwerkers (bijv. een hosting- of e-maildienst). We bewaren de gegevens alleen zo lang als nodig is om je vraag af te handelen, maximaal 24 maanden, tenzij de wet anders vereist." },
    "Vaše údaje neposkytujeme tretím stranám na marketingové účely. Uchovávame ich len po dobu nevyhnutnú na vybavenie vášho dopytu, najviac 24 mesiacov, ak zákon nevyžaduje inak.": { EN: "We do not share your data with third parties for marketing purposes. We keep it only for as long as needed to handle your enquiry, at most 24 months, unless the law requires otherwise.", DE: "Wir geben Ihre Daten nicht zu Marketingzwecken an Dritte weiter. Wir speichern sie nur so lange, wie es zur Bearbeitung Ihrer Anfrage nötig ist, höchstens 24 Monate, sofern das Gesetz nichts anderes verlangt.", NL: "We delen je gegevens niet met derden voor marketingdoeleinden. We bewaren ze alleen zo lang als nodig is om je vraag af te handelen, maximaal 24 maanden, tenzij de wet anders vereist." },
    "6. Vaše práva": { EN: "6. Your rights", DE: "6. Ihre Rechte", NL: "6. Jouw rechten" },
    "Máte právo na prístup k svojim údajom, ich opravu, vymazanie, obmedzenie spracovania, prenosnosť, ako aj právo namietať spracovanie a podať sťažnosť dozornému orgánu (Úrad na ochranu osobných údajov SR).": { EN: "You have the right to access your data, to have it corrected, erased, to restrict processing, to data portability, as well as the right to object to processing and to lodge a complaint with the supervisory authority (Office for Personal Data Protection of the Slovak Republic).", DE: "Sie haben das Recht auf Auskunft über Ihre Daten, deren Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit sowie das Recht auf Widerspruch gegen die Verarbeitung und auf Beschwerde bei der Aufsichtsbehörde (Amt für Datenschutz der Slowakischen Republik).", NL: "Je hebt het recht op inzage in je gegevens, correctie, verwijdering, beperking van de verwerking, overdraagbaarheid, evenals het recht om bezwaar te maken tegen de verwerking en een klacht in te dienen bij de toezichthoudende autoriteit (Bureau voor gegevensbescherming van de Slowaakse Republiek)." },
    "Máte právo na prístup k svojim údajom, ich opravu, vymazanie, obmedzenie spracovania, prenosnosť, ako aj právo namietať spracovanie a podať sťažnosť dozornému orgánu.": { EN: "You have the right to access your data, to have it corrected, erased, to restrict processing, to data portability, as well as the right to object to processing and to lodge a complaint with the supervisory authority.", DE: "Sie haben das Recht auf Auskunft über Ihre Daten, deren Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit sowie das Recht auf Widerspruch gegen die Verarbeitung und auf Beschwerde bei der Aufsichtsbehörde.", NL: "Je hebt het recht op inzage in je gegevens, correctie, verwijdering, beperking van de verwerking, overdraagbaarheid, evenals het recht om bezwaar te maken tegen de verwerking en een klacht in te dienen bij de toezichthoudende autoriteit." },
    "7. Kontakt": { EN: "7. Contact", DE: "7. Kontakt", NL: "7. Contact" },
    "V otázkach ochrany súkromia nás kontaktujte na": { EN: "For privacy questions, contact us at", DE: "Bei Fragen zum Datenschutz kontaktieren Sie uns unter", NL: "Voor privacyvragen kun je contact met ons opnemen via" },
    "alebo telefonicky na +421 911 657 234.": { EN: "or by phone at +421 911 657 234.", DE: "oder telefonisch unter +421 911 657 234.", NL: "of telefonisch op +421 911 657 234." },
    "alebo na +421 911 657 234.": { EN: "or at +421 911 657 234.", DE: "oder unter +421 911 657 234.", NL: "of op +421 911 657 234." },
    "alebo volajte na +421 911 657 234.": { EN: "or call +421 911 657 234.", DE: "oder rufen Sie +421 911 657 234 an.", NL: "of bel +421 911 657 234." },

    // ---- legal: terms ----
    "Podmienky používania tejto webovej stránky. Posledná aktualizácia: 7. júl 2026.": { EN: "Terms of use of this website. Last updated: 7 July 2026.", DE: "Nutzungsbedingungen dieser Website. Zuletzt aktualisiert: 7. Juli 2026.", NL: "Gebruiksvoorwaarden van deze website. Laatst bijgewerkt: 7 juli 2026." },
    "Prístupom na túto webovú stránku a jej používaním súhlasíte s týmito pravidlami používania. Ak s nimi nesúhlasíte, prosím, stránku nepoužívajte.": { EN: "By accessing and using this website you agree to these terms of use. If you do not agree with them, please do not use the site.", DE: "Durch den Zugriff auf diese Website und deren Nutzung stimmen Sie diesen Nutzungsbedingungen zu. Wenn Sie ihnen nicht zustimmen, nutzen Sie die Website bitte nicht.", NL: "Door deze website te bezoeken en te gebruiken ga je akkoord met deze gebruiksvoorwaarden. Als je er niet mee akkoord gaat, gebruik de site dan niet." },
    "Prístupom na túto webovú stránku a jej používaním súhlasíte s týmito pravidlami používania. Ak s nimi nesúhlasíte, prosím, stránku nepoužívajte. Fondré Studio si vyhradzuje právo tieto pravidlá kedykoľvek upraviť.": { EN: "By accessing and using this website you agree to these terms of use. If you do not agree with them, please do not use the site. Fondré Studio reserves the right to amend these terms at any time.", DE: "Durch den Zugriff auf diese Website und deren Nutzung stimmen Sie diesen Nutzungsbedingungen zu. Wenn Sie ihnen nicht zustimmen, nutzen Sie die Website bitte nicht. Fondré Studio behält sich das Recht vor, diese Bedingungen jederzeit zu ändern.", NL: "Door deze website te bezoeken en te gebruiken ga je akkoord met deze gebruiksvoorwaarden. Als je er niet mee akkoord gaat, gebruik de site dan niet. Fondré Studio behoudt zich het recht voor deze voorwaarden op elk moment te wijzigen." },
    "2. Používanie stránky": { EN: "2. Use of the site", DE: "2. Nutzung der Website", NL: "2. Gebruik van de site" },
    "Stránku a jej obsah môžete používať na osobné a informačné účely. Zaväzujete sa, že ju nebudete používať spôsobom, ktorý by:": { EN: "You may use the site and its content for personal and informational purposes. You agree not to use it in a way that would:", DE: "Sie dürfen die Website und ihre Inhalte für persönliche und informative Zwecke nutzen. Sie verpflichten sich, sie nicht in einer Weise zu nutzen, die:", NL: "Je mag de site en de inhoud ervan gebruiken voor persoonlijke en informatieve doeleinden. Je stemt ermee in de site niet te gebruiken op een manier die:" },
    "porušoval platné právne predpisy alebo práva tretích strán,": { EN: "breach applicable laws or the rights of third parties,", DE: "geltendes Recht oder Rechte Dritter verletzt,", NL: "geldende wetgeving of rechten van derden schendt," },
    "narušoval bezpečnosť, prevádzku alebo dostupnosť stránky,": { EN: "compromise the security, operation or availability of the site,", DE: "die Sicherheit, den Betrieb oder die Verfügbarkeit der Website beeinträchtigt,", NL: "de veiligheid, werking of beschikbaarheid van de site aantast," },
    "zahŕňal automatizovaný zber údajov bez nášho súhlasu.": { EN: "involve automated data collection without our consent.", DE: "automatisierte Datenerfassung ohne unsere Zustimmung umfasst.", NL: "geautomatiseerde gegevensverzameling zonder onze toestemming omvat." },
    "3. Duševné vlastníctvo": { EN: "3. Intellectual property", DE: "3. Geistiges Eigentum", NL: "3. Intellectueel eigendom" },
    "Všetok obsah na tejto stránke — texty, dizajn, grafika, logá, fotografie a ukážky projektov — je vlastníctvom Fondré Studio alebo príslušných partnerov a je chránený autorským právom.": { EN: "All content on this site — texts, design, graphics, logos, photographs and project samples — is the property of Fondré Studio or the respective partners and is protected by copyright.", DE: "Alle Inhalte dieser Website — Texte, Design, Grafiken, Logos, Fotos und Projektbeispiele — sind Eigentum von Fondré Studio oder der jeweiligen Partner und urheberrechtlich geschützt.", NL: "Alle inhoud op deze site — teksten, design, grafische elementen, logo's, foto's en projectvoorbeelden — is eigendom van Fondré Studio of de betreffende partners en wordt beschermd door auteursrecht." },
    "Všetok obsah na tejto stránke — texty, dizajn, grafika, logá, fotografie a ukážky projektov — je vlastníctvom Fondré Studio alebo príslušných partnerov a je chránený autorským právom. Bez predchádzajúceho písomného súhlasu ho nie je dovolené kopírovať, distribuovať ani komerčne využívať.": { EN: "All content on this site — texts, design, graphics, logos, photographs and project samples — is the property of Fondré Studio or the respective partners and is protected by copyright. It may not be copied, distributed or used commercially without prior written consent.", DE: "Alle Inhalte dieser Website — Texte, Design, Grafiken, Logos, Fotos und Projektbeispiele — sind Eigentum von Fondré Studio oder der jeweiligen Partner und urheberrechtlich geschützt. Ohne vorherige schriftliche Zustimmung dürfen sie nicht kopiert, verbreitet oder kommerziell genutzt werden.", NL: "Alle inhoud op deze site — teksten, design, grafische elementen, logo's, foto's en projectvoorbeelden — is eigendom van Fondré Studio of de betreffende partners en wordt beschermd door auteursrecht. Zonder voorafgaande schriftelijke toestemming mag deze niet worden gekopieerd, verspreid of commercieel gebruikt." },
    "4. Ukážky projektov": { EN: "4. Project samples", DE: "4. Projektbeispiele", NL: "4. Projectvoorbeelden" },
    "Projekty prezentované na stránke slúžia na ilustráciu našej práce. Niektoré boli realizované v rámci spolupráce s tretími stranami a príslušné ochranné známky a značky patria ich vlastníkom.": { EN: "The projects presented on the site serve to illustrate our work. Some were delivered in collaboration with third parties, and the respective trademarks and brands belong to their owners.", DE: "Die auf der Website gezeigten Projekte dienen der Veranschaulichung unserer Arbeit. Einige entstanden in Zusammenarbeit mit Dritten, und die jeweiligen Marken gehören ihren Inhabern.", NL: "De op de site getoonde projecten dienen ter illustratie van ons werk. Sommige zijn gerealiseerd in samenwerking met derden, en de betreffende handelsmerken en merken behoren toe aan hun eigenaren." },
    "Projekty prezentované na stránke slúžia na ilustráciu našej práce. Príslušné ochranné známky a značky patria ich vlastníkom.": { EN: "The projects presented on the site serve to illustrate our work. The respective trademarks and brands belong to their owners.", DE: "Die auf der Website gezeigten Projekte dienen der Veranschaulichung unserer Arbeit. Die jeweiligen Marken gehören ihren Inhabern.", NL: "De op de site getoonde projecten dienen ter illustratie van ons werk. De betreffende handelsmerken en merken behoren toe aan hun eigenaren." },
    "5. Obmedzenie zodpovednosti": { EN: "5. Limitation of liability", DE: "5. Haftungsbeschränkung", NL: "5. Beperking van aansprakelijkheid" },
    "Obsah stránky poskytujeme „tak, ako je\". Napriek starostlivosti pri jeho príprave nezaručujeme jeho úplnosť ani bezchybnosť a nezodpovedáme za prípadné škody vzniknuté použitím alebo nemožnosťou použitia stránky.": { EN: "We provide the site content \"as is\". Despite care in its preparation, we do not guarantee its completeness or accuracy and are not liable for any damages arising from the use or inability to use the site.", DE: "Wir stellen die Inhalte der Website „wie besehen\" bereit. Trotz Sorgfalt bei der Erstellung garantieren wir weder Vollständigkeit noch Fehlerfreiheit und haften nicht für etwaige Schäden aus der Nutzung oder Nichtnutzbarkeit der Website.", NL: "We bieden de inhoud van de site \"as is\" aan. Ondanks zorgvuldige voorbereiding garanderen we de volledigheid of juistheid niet en zijn we niet aansprakelijk voor eventuele schade door het gebruik of de onmogelijkheid tot gebruik van de site." },
    "Obsah stránky poskytujeme „tak, ako je\". Nezaručujeme jeho úplnosť ani bezchybnosť a nezodpovedáme za škody vzniknuté použitím alebo nemožnosťou použitia stránky.": { EN: "We provide the site content \"as is\". We do not guarantee its completeness or accuracy and are not liable for damages arising from the use or inability to use the site.", DE: "Wir stellen die Inhalte der Website „wie besehen\" bereit. Wir garantieren weder Vollständigkeit noch Fehlerfreiheit und haften nicht für Schäden aus der Nutzung oder Nichtnutzbarkeit der Website.", NL: "We bieden de inhoud van de site \"as is\" aan. We garanderen de volledigheid of juistheid niet en zijn niet aansprakelijk voor schade door het gebruik of de onmogelijkheid tot gebruik van de site." },
    "6. Odkazy tretích strán": { EN: "6. Third-party links", DE: "6. Links Dritter", NL: "6. Links van derden" },
    "Stránka môže obsahovať odkazy na externé weby. Za ich obsah a postupy ochrany súkromia nenesieme zodpovednosť a odporúčame oboznámiť sa s ich vlastnými podmienkami.": { EN: "The site may contain links to external websites. We are not responsible for their content and privacy practices and recommend reviewing their own terms.", DE: "Die Website kann Links zu externen Websites enthalten. Für deren Inhalte und Datenschutzpraktiken übernehmen wir keine Verantwortung und empfehlen, deren eigene Bedingungen zu lesen.", NL: "De site kan links naar externe websites bevatten. We zijn niet verantwoordelijk voor hun inhoud en privacypraktijken en raden aan hun eigen voorwaarden te bekijken." },
    "Stránka môže obsahovať odkazy na externé weby. Za ich obsah a postupy ochrany súkromia nenesieme zodpovednosť.": { EN: "The site may contain links to external websites. We are not responsible for their content and privacy practices.", DE: "Die Website kann Links zu externen Websites enthalten. Für deren Inhalte und Datenschutzpraktiken übernehmen wir keine Verantwortung.", NL: "De site kan links naar externe websites bevatten. We zijn niet verantwoordelijk voor hun inhoud en privacypraktijken." },
    "Otázky k týmto pravidlám nám pošlite na": { EN: "Send questions about these terms to", DE: "Fragen zu diesen Bedingungen senden Sie an", NL: "Stuur vragen over deze voorwaarden naar" }
  };

  var LANGS = { EN: 1, DE: 1, NL: 1 };

  function translateNodes(l) {
    var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode: function (n) {
        var p = n.parentNode; if (!p) return NodeFilter.FILTER_REJECT;
        var t = p.nodeName;
        if (t === 'SCRIPT' || t === 'STYLE' || t === 'NOSCRIPT') return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    var nodes = [], n;
    while (n = walker.nextNode()) nodes.push(n);
    nodes.forEach(function (node) {
      if (node.__i18nFull === undefined) {
        var core = node.nodeValue.trim();
        if (T[core]) { node.__i18nKey = core; node.__i18nFull = node.nodeValue; }
        else { node.__i18nFull = null; return; }
      }
      if (node.__i18nFull === null) return;
      var raw = node.__i18nFull, key = node.__i18nKey;
      var lead = raw.match(/^\s*/)[0], trail = raw.match(/\s*$/)[0];
      var out = (l !== 'SK' && T[key] && T[key][l]) ? T[key][l] : key;
      node.nodeValue = lead + out + trail;
    });
    // placeholders
    document.querySelectorAll('[placeholder]').forEach(function (el) {
      if (el.__i18nPh === undefined) {
        var v = (el.getAttribute('placeholder') || '').trim();
        if (T[v]) el.__i18nPh = v; else { el.__i18nPh = null; return; }
      }
      if (el.__i18nPh === null) return;
      var key = el.__i18nPh;
      el.setAttribute('placeholder', (l !== 'SK' && T[key] && T[key][l]) ? T[key][l] : key);
    });
  }

  window.__i18n = function (l) {
    if (l !== 'SK' && !LANGS[l]) l = 'SK';
    translateNodes(l);
    document.documentElement.setAttribute('data-lang', l);
    document.documentElement.setAttribute('lang', l.toLowerCase());
  };

  // apply saved language once the injected nav/footer exist
  window.addEventListener('load', function () {
    var saved; try { saved = localStorage.getItem('lang'); } catch (e) {}
    if (saved && saved !== 'SK') {
      window.__i18n(saved);
      var code = document.querySelector('.lang-code'); if (code) code.textContent = saved;
      document.querySelectorAll('.lang-menu button, .mnav-langs button').forEach(function (b) {
        b.classList.toggle('on', b.getAttribute('data-lang') === saved);
      });
    }
  });
})();
